@startuml
actor Исполнитель
participant "ProjectFlow System" as System
participant Менеджер

Исполнитель -> System : Перевести задачу в статус "В работе"
System -> Менеджер : Уведомление о начале работы
Исполнитель -> System : Перевести задачу в статус "Ревью"
System -> Менеджер : Запрос ревью
Менеджер -> System : Статус "Выполнено"
System -> Исполнитель : Оповещение об успешном завершении задачи
@enduml
