@startuml
package ProjectFlow {
  package core {
    [Аутентификация/Авторизация]
    [Управление пользователями]
  }
  package задачи {
    [Создание/редактирование задач]
    [Назначение]
    [Журнал изменений]
  }
  package команды {
    [Управление командами]
  }
  package отчеты {
    [KPI]
    [Дашборды]
  }
  package интеграция {
    [Интеграция с внешними сервисами]
  }
}

[Аутентификация/Авторизация] ..> [Управление пользователями]
[Создание/редактирование задач] ..> [Назначение]
[Журнал изменений] ..> [Создание/редактирование задач]
[Управление командами] ..> [Назначение]
[KPI] ..> [Дашборды]
[Интеграция с внешними сервисами] ..> [KPI]
@enduml
