@startuml
actor Пользователь
participant Мобильное_приложение
participant "ProjectFlow System" as Server

Пользователь -> Мобильное_приложение : Открывает offline-задачи
Мобильное_приложение -> Server : При появлении интернета — отправка новых данных
Server -> Мобильное_приложение : Подтверждение синхронизации, обновлённые статусы задач
@enduml
