@startuml
object Проект_CRM {
  название = "CRM для продаж"
}
object Спринт_1 {
  статус = "Active"
}
object Задача_101 {
  статус = "В работе"
  исполнитель = "Иванов"
}
object Задача_102 {
  статус = "Новая"
  исполнитель = "Петрова"
}
object Пользователь_Иванов
object Пользователь_Петрова

Проект_CRM -- Спринт_1
Спринт_1 -- Задача_101
Спринт_1 -- Задача_102
Задача_101 -- Пользователь_Иванов
Задача_102 -- Пользователь_Петрова
@enduml
